[package]
name = "clipsyncmac"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard-rs = "0.1.7"
core-foundation = "0.9.4"
daemonize-me = "2.0.1"
lazy_static = "1.5.0"
socket2 = { version = "0.5.7", features = ["all"] }
